import { Event, EventType, EventCategory, RepeatOption, User } from './types';

export const mockUser: User = {
  id: '1',
  name: 'João Silva',
  email: 'joao.silva@email.com',
  phone: '+55 11 99999-9999',
  timezone: 'America/Sao_Paulo',
};

export const eventTypes: EventType[] = [
  { id: '1', name: 'Reunião', color: '#3b82f6', icon: 'users' },
  { id: '2', name: 'Tarefa', color: '#10b981', icon: 'check-circle' },
  { id: '3', name: 'Compromisso', color: '#f59e0b', icon: 'calendar' },
  { id: '4', name: 'Lembrete', color: '#8b5cf6', icon: 'bell' },
  { id: '5', name: 'Pessoal', color: '#ec4899', icon: 'heart' },
];

export const eventCategories: EventCategory[] = [
  { id: '1', name: 'Trabalho', color: '#3b82f6' },
  { id: '2', name: 'Pessoal', color: '#10b981' },
  { id: '3', name: 'Saúde', color: '#f59e0b' },
  { id: '4', name: 'Educação', color: '#8b5cf6' },
  { id: '5', name: 'Família', color: '#ec4899' },
];

export const repeatOptions: RepeatOption[] = [
  { id: '1', name: 'Não repetir', value: 'none' },
  { id: '2', name: 'Diariamente', value: 'daily' },
  { id: '3', name: 'Semanalmente', value: 'weekly' },
  { id: '4', name: 'Mensalmente', value: 'monthly' },
  { id: '5', name: 'Anualmente', value: 'yearly' },
];

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Reunião com Cliente',
    description: 'Discutir proposta do novo projeto',
    startDate: new Date(2025, 10, 21),
    endDate: new Date(2025, 10, 21),
    startTime: '09:00',
    endTime: '10:30',
    type: 'Reunião',
    category: 'Trabalho',
    priority: 'high',
    location: 'Sala de Reuniões 1',
    participants: 'Maria Santos, Pedro Costa',
    reminder: '15min',
    repeat: 'none',
    color: '#3b82f6',
    notes: 'Levar apresentação do projeto',
  },
  {
    id: '2',
    title: 'Consulta Médica',
    description: 'Check-up anual',
    startDate: new Date(2025, 10, 22),
    endDate: new Date(2025, 10, 22),
    startTime: '14:00',
    endTime: '15:00',
    type: 'Compromisso',
    category: 'Saúde',
    priority: 'medium',
    location: 'Clínica Central',
    reminder: '1hour',
    repeat: 'yearly',
    color: '#f59e0b',
  },
  {
    id: '3',
    title: 'Aniversário da Maria',
    description: 'Festa de aniversário',
    startDate: new Date(2025, 10, 25),
    endDate: new Date(2025, 10, 25),
    startTime: '19:00',
    endTime: '23:00',
    type: 'Pessoal',
    category: 'Família',
    priority: 'high',
    location: 'Chácara da família',
    reminder: '1day',
    repeat: 'yearly',
    color: '#ec4899',
    notes: 'Comprar presente',
  },
  {
    id: '4',
    title: 'Entregar Relatório',
    description: 'Relatório mensal de vendas',
    startDate: new Date(2025, 10, 24),
    endDate: new Date(2025, 10, 24),
    startTime: '17:00',
    endTime: '18:00',
    type: 'Tarefa',
    category: 'Trabalho',
    priority: 'high',
    location: 'Escritório',
    reminder: '2hours',
    repeat: 'monthly',
    color: '#10b981',
  },
  {
    id: '5',
    title: 'Academia',
    description: 'Treino de força',
    startDate: new Date(2025, 10, 21),
    endDate: new Date(2025, 10, 21),
    startTime: '18:00',
    endTime: '19:30',
    type: 'Pessoal',
    category: 'Saúde',
    priority: 'medium',
    location: 'Smart Fit',
    reminder: '30min',
    repeat: 'weekly',
    color: '#ec4899',
  },
];
